#!/usr/bin/env bash
# Vendor the canonical tables and crate version into this package before
# packing. The repository keeps no duplicates: `tables/` and `Cargo.toml`
# at the cletter root stay canonical; `src/generated/` and
# `typst/generated/` are regenerated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

mkdir -p "$HERE/src/generated" "$ROOT/typst/generated"

VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*"\(.*\)"/\1/')"

python3 - "$HERE" "$ROOT" "$VERSION" <<'EOF'
import json
import sys

here, root, version = sys.argv[1], sys.argv[2], sys.argv[3]
with open(f"{root}/tables/locales.json", encoding="utf-8") as handle:
    locales = json.load(handle)
with open(f"{root}/tables/countries.json", encoding="utf-8") as handle:
    countries = json.load(handle)
out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    f"export const PACKAGE_VERSION: string = {json.dumps(version)};\n"
    f"export const LETTER_TABLES: unknown = {json.dumps({'LOCALES': locales, 'COUNTRIES': countries}, ensure_ascii=False)};\n"
)
with open(f"{here}/src/generated/tables.ts", "w", encoding="utf-8") as handle:
    handle.write(out)


def typst_str(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def typst_value(value, indent):
    pad = '  ' * indent
    if isinstance(value, dict):
        rows = [f"{pad}{typst_str(k)}: {typst_value(v, indent + 1)}" for k, v in value.items()]
        return "(\n" + ",\n".join(rows) + ",\n" + '  ' * (indent - 1) + ")"
    if isinstance(value, list):
        rows = [f"{pad}{typst_value(v, indent + 1)}" for v in value]
        return "(\n" + ",\n".join(rows) + ",\n" + '  ' * (indent - 1) + ")"
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if value is None:
        return 'none'
    return typst_str(value)


typ = (
    "// GENERATED by js/@corbet-labs/cletter/scripts/sync-assets.sh — do not edit.\n"
    "#let locales-table = " + typst_value(locales, 1) + "\n"
    "#let countries-table = " + typst_value(countries, 1) + "\n"
)
with open(f"{root}/typst/generated/tables.typ", "w", encoding="utf-8") as handle:
    handle.write(typ)
print(f"synced tables/locales.json + countries.json, version {version}")
EOF

# Keep Python's packaged tables and license texts aligned with the canonical root.
python3 "$ROOT/scripts/sync-python.py"
