"""Generate Python tables and retain the canonical distribution license texts."""
import json
import shutil
import tomllib
from pathlib import Path
from pprint import pformat

root = Path(__file__).resolve().parent.parent
name = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))["package"]["name"]
tables = {p.stem: json.loads(p.read_text(encoding="utf-8")) for p in sorted((root / "tables").glob("*.json"))}
out = root / "py" / name / "_tables.py"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("# Generated by scripts/sync-python.py; edit tables/*.json instead.\nTABLES = " + pformat(tables, sort_dicts=False, width=100) + "\n", encoding="utf-8")

licenses = root / "py" / "LICENSES"
licenses.mkdir(parents=True, exist_ok=True)
sources = [path for path in sorted((root / "LICENSES").iterdir()) if path.is_file()]
expected = {source.name for source in sources}
for stale in licenses.iterdir():
    if stale.is_file() and stale.name not in expected:
        stale.unlink()
for source in sources:
    shutil.copyfile(source, licenses / source.name)
